---
# tasks file for gurkalov.deploy_user
- name: Create private key (copy)
  local_action: copy content={{ private_key }} dest={{ private_key_path }}
  run_once: true
  when: private_key != ""

- name: Create public key (copy)
  local_action: copy content={{ public_key }} dest={{ public_key_path }}
  run_once: true
  when: private_key != ""

- name: Check for private key
  local_action: stat path={{ private_key_path }}
  run_once: true
  register: stat_private_key

- name: Create private key (generate)
  local_action: command ssh-keygen -b 2048 -t rsa -f {{ private_key_path }} -q -N ""
  run_once: true
  when: stat_private_key.stat.exists == False

- name: Setup authorized_keys
  authorized_key:
    key: "{{ item }}"
    user: "{{ user_name }}"
    state: present
  with_file: "{{ public_keys }}"

- name: Set user password
  user:
    append: true
    groups: "{{ (user_groups | join(',')) }}"
    name: "{{ user_name }}"
    password: "{{ (user_password | password_hash('sha512')) }}"
    shell: "{{ user_shell }}"
    state: present
    update_password: always
  when: user_password != ""
