---
# tasks file for gurkalov.deploy_user
- name: Create private key (copy)
  copy:
    content: "{{ private_key }}"
    dest: "{{ private_key_path }}"
  delegate_to: localhost
  run_once: true
  when: private_key | length > 0

- name: Create public key (copy)
  copy:
    content: "{{ public_key }}"
    dest: "{{ public_key_path }}"
  delegate_to: localhost
  run_once: true
  when: private_key | length > 0

- name: Check for private key
  stat:
    path: "{{ private_key_path }}"
  delegate_to: localhost
  run_once: true
  register: stat_private_key

- name: Create private key (generate)
  command: ssh-keygen -b 2048 -t rsa -f {{ private_key_path }} -q -N ""
  delegate_to: localhost
  run_once: true
  when: not stat_private_key.stat.exists

- name: Setup authorized_keys
  authorized_key:
    key: "{{ item }}"
    user: "{{ user_name }}"
    state: present
  with_file: "{{ public_keys }}"

- name: Set user password
  user:
    append: true
    groups: "{{ (user_groups | join(',')) }}"
    name: "{{ user_name }}"
    password: "{{ (user_password | password_hash('sha512')) }}"
    shell: "{{ user_shell }}"
    state: present
    update_password: always
  when: user_password | length > 0

- name: Disable passwordless sudo
  file:
    path: "/etc/sudoers.d/{{ user_name }}"
    state: absent
  when: not enable_passwordless_sudo
