---
- name: Create deploy user on all hosts.
  hosts: all
  pre_tasks:
    - name: Create fake SSH key
      copy: content="ssh-rsa foo hello@world" dest=/tmp/id_rsa.pub mode=0640
      delegate_to: localhost
  roles:
    - role: ansible-deploy-user

  vars_files:
    - ./playbook-vars.yml
